// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// pio_i2s_slave //
// ------------- //

#define pio_i2s_slave_wrap_target 1
#define pio_i2s_slave_wrap 4

static const uint16_t pio_i2s_slave_program_instructions[] = {
    0x20a2, //  0: wait   1 pin, 2                   
            //     .wrap_target
    0x2022, //  1: wait   0 pin, 2                   
    0x2021, //  2: wait   0 pin, 1                   
    0x20a1, //  3: wait   1 pin, 1                   
    0x4000, //  4: in     pins, 32                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_i2s_slave_program = {
    .instructions = pio_i2s_slave_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config pio_i2s_slave_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_i2s_slave_wrap_target, offset + pio_i2s_slave_wrap);
    return c;
}
#endif

