// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pio_uart_tx //
// ----------- //

#define pio_uart_tx_wrap_target 0
#define pio_uart_tx_wrap 3

static const uint16_t pio_uart_tx_program_instructions[] = {
            //     .wrap_target
    0x9fa0, //  0: pull   block           side 1 [7] 
    0xf727, //  1: set    x, 7            side 0 [7] 
    0x6001, //  2: out    pins, 1                    
    0x0642, //  3: jmp    x--, 2                 [6] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_uart_tx_program = {
    .instructions = pio_uart_tx_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config pio_uart_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_uart_tx_wrap_target, offset + pio_uart_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

